### ISSUE TITLE
Missing use cases

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#120]
- [ ] Geschäftsprozess: Passwort zurücksetzen
```
Exception in thread "pool-2-thread-1" java.lang.NullPointerException
    at me.metlabnews.Model.BusinessLogic.UserManager.changePassword(UserManager.java:722)
    at me.metlabnews.Presentation.Presenter.lambda$null$22(Presenter.java:123)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

- [ ] Geschäftsprozess: Interessenprofil erstellen bzw. ändern
```
Aendern der Profile  geht nicht; kein UI
```
- [x] Geschäftsprozess: Pressespiegel ansehen
```
Wird nicht online angezeigt?
```
vgl #118 

- [ ] Geschäftsprozess: Vorlage für ein Interessenprofil erstellen / bearbeiten
```
Aendern geht nicht, kein UI
nur eine Quelle bei Mitarbeiter ausgewaehlt
```

**Comment by Toberto91** [comment]
too late
