### ISSUE TITLE
Infinite Recursion zwischen Logger und ConfigurationManager

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#47]
Siehe Titel. Hat jemand anderes das gleiche Problem auf dev? Ich bekomme einen StackOverflow sobald ich den Server starten will. So was muss doch auffallen... Bitte vorm comitten wenigstens rudimentär testen.
StackTrace:
```
at me.metlabnews.Model.DataAccess.ConfigurationManager.returnProperty(ConfigurationManager.java:303)
	at me.metlabnews.Model.DataAccess.ConfigurationManager.getFilteredPriorities(ConfigurationManager.java:262)
	at me.metlabnews.Model.Common.Logger.isPriorityFiltered(Logger.java:164)
	at me.metlabnews.Model.Common.Logger.log(Logger.java:269)
	at me.metlabnews.Model.DataAccess.ConfigurationManager.returnProperty(ConfigurationManager.java:303)

**Comment by ede1998** [comment]
Wurde das in commit d3f1c18bade0ec8670fae66aa4a5a3d64d80b1df geloest? Wenn ja bitte schliessen.

**Comment by MarcoRempfer** [comment]
Ist gefixt
