### ISSUE TITLE
NullPointerException auf Server - bitte pruefen (Presenter)

### ISSUE THREAD

**Issue by ede1998** [InvisibleUSA/METLAB_News#67]
Passiert unregelmaessig, vermutlich wenn jemand die website verlaesst.
StackTrace im Log:
```
Apr 25, 2018 5:01:34 AM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE:
java.lang.NullPointerException
        at me.metlabnews.Presentation.Presenter.disconnect(Presenter.java:135)
        at me.metlabnews.UserInterface.MainUI$MainUIServlet.sessionDestroy(MainUI.java:372)
        at com.vaadin.server.VaadinService.lambda$fireSessionDestroy$1(VaadinService.java:554)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:2046)
        at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1019)
        at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2011)
        at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1977)
        at com.vaadin.server.VaadinSession.access(VaadinSession.java:1418)
        at com.vaadin.server.VaadinService.fireSessionDestroy(VaadinService.java:528)
        at com.vaadin.server.VaadinSession.valueUnbound(VaadinSession.java:314)
        at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1784)
        at org.apache.catalina.session.StandardSession.expire(StandardSession.java:856)
        at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:659)
        at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:573)
        at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:558)
        at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5406)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1396)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1400)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1368)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by MarcoRempfer** [comment]
Sollte gefixt sein.

**Comment by ede1998** [comment]
Dann mach es auch zu ;)
