### ISSUE TITLE
MainUI wird nicht angezeigt

### ISSUE THREAD

**Issue by InvisibleUSA** [InvisibleUSA/METLAB_News#72]
Beim zugriff auf die localhost Website kommt folgende Fehlermeldung:

`java.lang.IllegalArgumentException: sender is not associated with a session
	at me.metlabnews.Presentation.Presenter.whoAmI(Presenter.java:153)
	at me.metlabnews.UserInterface.MainUI.whoAmI(MainUI.java:192)
	at me.metlabnews.UserInterface.Views.SubscriberDashboardView.<init>(SubscriberDashboardView.java:48)
	at me.metlabnews.UserInterface.MainUI.init(MainUI.java:52)
	at com.vaadin.ui.UI.doInit(UI.java:771)
...`

Website wird nicht angezeigt

**Comment by InvisibleUSA** [comment]
@vulpesaquae oder @MarcoRempfer wird das heute noch gefixed??

**Comment by MarcoRempfer** [comment]
Ja, geschätzt so gegen 20:00 Uhr

**Comment by MarcoRempfer** [comment]
Wohl eher doch nicht
